server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: "${SERVICE_REGISTRY:http://localhost:8761/eureka/}"

spring:
  application:
    name: manage-service
  zipkin:
    baseUrl: "${ZIPKIN_SERVER:http://localhost:9411/}"
  config:
    import: "${CONFIG_SERVER:optional:configserver:http://localhost:8088}"

management:
  zipkin:
    tracing:
      endpoint: "${ZIPKIN_SERVER:http://localhost:9411/api/v2/spans}"
  tracing:
    sampling:
      probability: 1.0

logging.level:
  com.akshay.gitface.manageservice.client.GithubClient: INFO