server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: "${SERVICE_REGISTRY:http://localhost:8761/eureka/}"

spring:
  zipkin:
    baseUrl: "${ZIPKIN_SERVER:http://localhost:9411/}"

management:
  zipkin:
    tracing:
      endpoint: "${ZIPKIN_SERVER:http://localhost:9411/api/v2/spans}"
  tracing:
    sampling:
      probability: 1.0