server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: "${SERVICE_REGISTRY:http://localhost:8761/eureka/}"

management:
  tracing:
    sampling:
      probability: 1.0


spring:
#  main:
#    web-application-type: servlet
#    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  config:
    import: "${CONFIG_SERVER:optional:configserver:http://localhost:8088}"
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: "${GITHUB_CLIENT_ID:id}"
            clientSecret: "${GITHUB_CLIENT_SECRET:secret}"
            scope:
              - repo
              - user
              - workflow
  cloud:
    gateway:
      routes:
        - id: manage-service
          uri: lb://manage-service
          predicates:
            - Path=/gitface/**
          filters:
            - TokenRelay=